name: Secret Scanning with GitGuardian

on:
  push:
    branches:
      - main  # You can specify the branch you want to trigger the workflow on

jobs:
  secret_scan:
    name: Secret Scanning
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # This action checks out your repository's code
      
      - name: Install GitGuardian CLI
        run: curl -LsS https://raw.githubusercontent.com/GitGuardian/gg-shield/main/install.sh | bash
                             # Install the GitGuardian CLI tool
      
      - name: Scan for Secrets
        run: ggshield scan --no-api --format=json > gitguardian-report.json  # Run GitGuardian to scan for secrets in your codebase and save the results in a JSON file

      - name: Upload GitGuardian Report
        uses: actions/upload-artifact@v2
        with:
          name: gitguardian-report
          path: gitguardian-report.json  # Upload the GitGuardian report as an artifact for further analysis
