name: Snyk Java Hardcoded Values Scan

on:
  push:
    branches:
      - main

jobs:
  snyk_scan_java:
    name: Snyk Java Hardcoded Values Scan
    runs-on: ubuntu

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.1

      - name: Install Snyk CLI
        run: |
          npm install -g snyk

      - name: Snyk Java Hardcoded Values Scan
        run: |
          snyk auth ${{ secrets.SNYK_TOKEN }}
          snyk test --all-sub-projects --language=java --fail-on=upgrade --json > snyk_report.json
