name: Snyk Java Hardcoded Values Scan

on: push
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    env:
      MYSQL_HOST_WITH_PORT: "34.172.203.60:3306"
      MYSQL_DB_NAME: wine
      MYSQL_USER: root
      MYSQL_PASSWORD: manager
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.1

      - name: Install Snyk CLI
        run: |
          npm install -g snyk

      - name: Snyk Java Hardcoded Values Scan
        continue-on-error: true
        run: |
          snyk auth ${{ secrets.SNYK_TOKEN }}
          snyk code test --json
          

